### ISSUE TITLE
Problems with PyQt5

### ISSUE THREAD

**Issue by ctheissen** [BU-hammerTeam/PyHammer#13]
Hi Everyone, just checked out the developer-branch and I'm getting the following error:

`ctheissen$ python3 pyhammer.py`
`Traceback (most recent call last):`
  `File "pyhammer.py", line 1, in <module>`
    `from pyhamimports import *`
  `File "/Users/ctheissen/repos/PyHammer/pyhamimports.py", line 43, in <module>`
   `from PyQt5.QWidgets import *`
`ModuleNotFoundError: No module named 'PyQt5.QWidgets'`

Seems you need to chance `'PyQt5.QWidgets'` to `'PyQt5.QtWidgets'`

**Comment by zephyr5050** [comment]
Simple typo, thanks for pointing it out.
