### ISSUE TITLE
GUI windows should open at the top of the screen

### ISSUE THREAD

**Issue by ctheissen** [BU-hammerTeam/PyHammer#15]
This might just be a personal preference issue, but the GUI windows are about as big as my screen. So when the window pops up halfway down and I have to drag it to the top it's a little annoying. I feel this should be an easy fix in somewhere in the widgets, but I could be wrong.

**Comment by zephyr5050** [comment]
Try taking out the `self.move(200,200)` lines and see how that helps. There's one in `pyhammer.py` and another in `eyecheck.py`, one for each GUI. I think then by default it will set the window more or less in the center of the screen.

**Comment by ctheissen** [comment]
Nope, that didn't fix it.

**Comment by zephyr5050** [comment]
Perhaps then `self.move(0,0)`. That should force the window to appear in the upper-left hand corner of the screen.

**Comment by ctheissen** [comment]
Yes, that fixed it. I think it's okay to move it a little bit horizontal, but I wouldn't move it vertical.
