### ISSUE TITLE
syntax error in pyhammer

### ISSUE THREAD

**Issue by stephtdouglas** [BU-hammerTeam/PyHammer#19]
when I try to run pyhammer, on the command line, I get the following error
```
  File "pyhammer.py", line 1, in <module>
    from pyhamimports import *
  File "/home/stephanie/code/python/PyHammer/pyhamimports.py", line 25, in <module>
    import numpy as np
ImportError: No module named 'numpy'
```
even though numpy is installed and I can access it in other scripts. 

If I try to run in ipython, I get the following syntax error

```
  File "/home/stephanie/code/python/PyHammer/pyhammer.py", line 77
    print(i+1, ') Processing ', os.path.basename(fname), sep = '')
                                                             ^
SyntaxError: invalid syntax

```

I'm running from the PyHammer folder itself, and I have tried both the latest release version and the current github version. I'm running in Python 3.4

**Comment by zephyr5050** [comment]
Can you specify what operating system/version you're running on? It looks linux-based at the very least, but it may be useful to know.

**Comment by stephtdouglas** [comment]
I'm on Linux running in a Conda environment. It seems to have been a Anaconda problem, sorry about that.
