### ISSUE TITLE
Create environment.yml to simplify installation process

### ISSUE THREAD

**Issue by TarekHC** [BU-hammerTeam/PyHammer#23]
Hi all, 

Thank you for developing and maintaining this cool tool. I just came across it today and it is exactly what I need! :)

Today I lost some time with the installation of this package with conda, and I think the simplest/cleanest solution would be to add a "environment.yml" file to the project. Do you think this would be possible? I could help with that.

**Comment by zephyr5050** [comment]
PyHammer is intended to be run as a standalone program, not to be installed as a module and imported. For full instructions, see our [Wiki page](https://github.com/BU-hammerTeam/PyHammer/wiki/Running-PyHammer).

Is there another way in which you were trying to use PyHammer?

**Comment by TarekHC** [comment]
Oh, I see. Aparently I got confused with the existence of this conda package:

https://anaconda.org/hargup/pyhammer

Thank you for the feedback!
