### ISSUE TITLE
nanfunctions.py ValueError: All Nan Slice Encountered

### ISSUE THREAD

**Issue by JosephKarpinski** [BU-hammerTeam/PyHammer#25]
This abend happens to often when processing multiple FITS file.
Have to remove the bad FITS file from control file and restart the process.
Program should bypass the FITS file and continue processing. 
Problem program nanfunctions.py
Def nanargmin
Line 406

![0aa8e903-8b5a-4698-9510-f3f9667d7257](https://user-images.githubusercontent.com/37123616/44067394-45effdfa-9f43-11e8-8a03-9f01147c13c5.jpeg)

**Comment by zephyr5050** [comment]
Implemented a potential fix on the [Developer Branch](https://github.com/BU-hammerTeam/PyHammer/tree/Developer-Branch). Try it out and let me know if this works for you. If it does, we can get it pushed into master.

**Comment by JosephKarpinski** [comment]
Is this new?

[cid:CD3E25C3-B1D4-4FA1-8812-EB39CF668EAF]



On Aug 13, 2018, at 10:45 PM, zephyr5050 <notifications@github.com<mailto:notifications@github.com>> wrote:


Implemented a potential fix on the Developer Branch<https://github.com/BU-hammerTeam/PyHammer/tree/Developer-Branch>. Try it out and let me know if this works for you. If it does, we can get it pushed into master.

**Comment by JosephKarpinski** [comment]
More testing:

[cid:C655FAC0-2E35-4B48-88AF-69A96C2F4EAE]

On Aug 13, 2018, at 10:45 PM, zephyr5050 <notifications@github.com<mailto:notifications@github.com>> wrote:


Implemented a potential fix on the Developer Branch<https://github.com/BU-hammerTeam/PyHammer/tree/Developer-Branch>. Try it out and let me know if this works for you. If it does, we can get it pushed into master.

**Comment by JosephKarpinski** [comment]
Still a bends.
See attached image.

[image1.jpeg]


Sent from my iPhone

On Aug 18, 2018, at 5:24 PM, zephyr5050 <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm sorry, I don't see anything in your comments. Did you intend to attach a picture or something?

**Comment by zephyr5050** [comment]
Your images don't appear to be attached properly and I'm not sure what you mean by saying it is still a bends.

**Comment by JosephKarpinski** [comment]
Hmm, replies via email do not seem to map attachments to GitHub comments.
Will reply directly via the website.
Here’s the latest screen print:
![494930b1-b246-470f-99d7-000e860bb34f](https://user-images.githubusercontent.com/37123616/44309847-b7dff900-a39a-11e8-9ca7-c910158c3218.jpeg)
![508390e8-902f-4e47-bd23-266dbf33e985](https://user-images.githubusercontent.com/37123616/44309848-b7dff900-a39a-11e8-930b-61351d5b48df.jpeg)

**Comment by JosephKarpinski** [comment]
Replied directly on GitHubs website.
Attaching previously sent screen prints.
Please review.
Thanks.

Sent from my iPad

On Aug 18, 2018, at 9:41 PM, zephyr5050 <notifications@github.com<mailto:notifications@github.com>> wrote:


Your images don't appear to be attached properly and I'm not sure what you mean by saying it is still a bends.

**Comment by zephyr5050** [comment]
Sorry to take so long to get back to this issue. But should be fixed on the developer branch. Feel free to check it out and let me know if you have any issues. If you don't see anything we can go ahead and push this into master.
