### ISSUE TITLE
All PyHammer Documented 'Giant' Star Templates are Missing

### ISSUE THREAD

**Issue by JosephKarpinski** [BU-hammerTeam/PyHammer#26]
The paper on PyHammer documents a large number of 'Giant' coadded spectra templates for all star subclasses. None of them exist in the PyHammer tool, only 'Dwarf' template FITS files.

[http://iopscience.iop.org/0067-0049/230/2/16/suppdata/apjsaa656dt2_mrt.txt](url)

Is there a link where we can download the missing templates?

See attached sample of some of the documented missing 'Giant' templates:

![missing_1](https://user-images.githubusercontent.com/37123616/46511236-67720d00-c81b-11e8-81b8-1f2cce95298d.jpeg)

**Comment by aurorayk** [comment]
The giant templates are available on the zenodo page associated with the Kesseli+2017 paper: https://zenodo.org/record/321394#.W7exCthKi8o

**Comment by aurorayk** [comment]
Awesome!
