### ISSUE TITLE
PyHammer UnboundLocalError

### ISSUE THREAD

**Issue by JosephKarpinski** [BU-hammerTeam/PyHammer#29]
See attachment:
UnboundLocalError: local variable 'snVal' referenced before assignment.
Workaround, remove last file processed at time of abend from control file and restart.

![pyhammer_unboundlocalerror](https://user-images.githubusercontent.com/37123616/46704549-8bf22e80-cbf9-11e8-9614-64e3ed4c3505.jpeg)

**Comment by zephyr5050** [comment]
Issue should have been fixed in commit [0152715](https://github.com/BU-hammerTeam/PyHammer/commit/0152715b73aab476799c0fcba53168975ef53c52) on developer branch. Check out the lastest of that branch and let me know if this resolves your issue.

**Comment by JosephKarpinski** [comment]
Just tried the new PyHammer code.
Getting UnboundLocalError in two different location:
 - line 128 when new lineOutfile is turned on
Josephs-iMac:~ josephkarpinski$ python3 new_pyhammer.py -f -i downloads/out.txt
1) Processing bad_A4 (G_165-39)_FeH[-2.32]_spec-3588-55184-0392.fits
2) Processing bad_A9V (154660)_FeH[-2.32]_spec-3590-55201-0318.fits
Traceback (most recent call last):
  File "new_pyhammer.py", line 846, in goToMain
    main(self.options)
  File "new_pyhammer.py", line 128, in main
    lineOutfile.write(fname + ',' + str(value[0]) + ',' + str(value[1])+',')
UnboundLocalError: local variable 'lineOutfile' referenced before assignment
Abort trap: 6

- line 193 when new lineOutfile is turned off
Josephs-iMac:~ josephkarpinski$ python3 new_pyhammer.py -f -i downloads/out.txt
1) Processing bad_A4 (G_165-39)_FeH[-2.32]_spec-3588-55184-0392.fits
2) Processing bad_A9V (154660)_FeH[-2.32]_spec-3590-55201-0318.fits
3) Processing bad_A9V (154660)_FeH[0.25]_spec-3609-55201-0112.fits
4) Processing bad_CV_FeH[0.17]_spec-5848-56029-0134.fits
5) Processing bad_F5Ib... (17463)_FeH[0.17]_spec-3609-55201-0018.fits
6) Processing bad_F6III (61064)_FeH[0.09]_spec-3606-55182-0454.fits
7) Processing bad_F8V (G_243-63)_FeH[-0.05]_spec-3587-55182-0006.fits
8) Processing bad_K1_FeH[0.05]_spec-0792-52353-0217.fits
9) Processing spec-0266-51630-0015.fits
10) Processing spec-0618-52049-0372.fits
11) Processing spec-1079-52621-0509.fits
Traceback (most recent call last):
  File "new_pyhammer.py", line 846, in goToMain
    main(self.options)
  File "new_pyhammer.py", line 193, in main
    lineOutfile.close()
UnboundLocalError: local variable 'lineOutfile' referenced before assignment
Abort trap: 6

**Comment by JosephKarpinski** [comment]
Updated entry on PyHammer issues web site.
UnboundLocalError in two locations.
See update.

Sent from my iPad

On Oct 11, 2018, at 10:15 PM, zephyr5050 <notifications@github.com<mailto:notifications@github.com>> wrote:


Issue should have been fixed in commit 0152715<https://github.com/BU-hammerTeam/PyHammer/commit/0152715b73aab476799c0fcba53168975ef53c52> on developer branch. Check out the lastest of that branch and let me know if this resolves your issue.

**Comment by zephyr5050** [comment]
Made more updates. Check out developer branch and give it a go.

**Comment by JosephKarpinski** [comment]
Looks good!
Put it through multiple known NaN abend FITS files with no issues.

Sent from my iPhone

On Oct 13, 2018, at 10:14 AM, zephyr5050 <notifications@github.com<mailto:notifications@github.com>> wrote:


Made more updates. Check out developer branch and give it a go.
