### ISSUE TITLE
PyHammer line 125 Remove Leading Spaces From spectralIndices.csv Column Names

### ISSUE THREAD

**Issue by JosephKarpinski** [BU-hammerTeam/PyHammer#31]
PyHammer line 125 remove leading spaces from spectralIndices.csv column names.
When importing spectralIndices.csv into a Python Dataframe, the column names are unusable because of leading spaces. Removing the blank spaces infront of each column name in PyHammer line 125 fixes the usability issue.
See attached:

![leading_spaces_error](https://user-images.githubusercontent.com/37123616/46870492-c4158f00-cdfc-11e8-8707-d31901b6aee1.jpeg)

**Comment by aurorayk** [comment]
deleted the leading spaces in the developer branch. If this solves the issue we will push the lineOutfile part of the code to the main branch.

**Comment by JosephKarpinski** [comment]
Thanks!

BTW, there are still issues with the lineOutfile part of the code:

Updated entry on PyHammer issues web site.
UnboundLocalError in two locations.
See update.

Sent from my iPhone

On Oct 12, 2018, at 2:45 PM, Aurora Kesseli <notifications@github.com<mailto:notifications@github.com>> wrote:


deleted the leading spaces in the developer branch. If this solves the issue we will push the lineOutfile part of the code to the main branch.
