### ISSUE TITLE
Doc Mismatch: 'The Template Spectra' documentation versus as seen in Spectrum.py

### ISSUE THREAD

**Issue by JosephKarpinski** [BU-hammerTeam/PyHammer#32]
Anyone using the new feature in PyHammer to generate a sprectralIndices.csv may look for definitions of the spectra line indices. Those found in the paper "An Empirical Template Library of Stellar Spectra for a Wide Range of Spectral Classes, Luminosity Classes, and Metallicities Using SDSS BOSS Spectra" 
link "The Template Spectra" differ from what actually is used in spectrum.py by labels and wavelength ranges used in creating each spectra indices. Possibly update the paper link with matching label and wavelength values, to clarify any confusion or concerns?

[http://iopscience.iop.org/0067-0049/230/2/16/suppdata/apjsaa656dt2_mrt.txt](url)

![template spectra doc mismatch](https://user-images.githubusercontent.com/37123616/46905564-a65f2d00-cec3-11e8-9001-be144a0b8eb2.jpeg)

**Comment by zephyr5050** [comment]
The paper is a published paper and cannot be amended. Unfortunately, it cannot keep up with any changes to PyHammer. However, we can change the wiki documentation on this GitHub page to keep up to date. I will close this issue for now though.

**Comment by JosephKarpinski** [comment]
Maybe an update on the GitHub site when the new spectra line feature in PyHammer is generally released?

Sent from my iPhone

On Oct 13, 2018, at 9:56 AM, zephyr5050 <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #32<https://github.com/BU-hammerTeam/PyHammer/issues/32>.

**Comment by zephyr5050** [comment]
The wiki page has been updated with the changes. All recent changes have been merged into the master branch and tagged as a new release.
