### ISSUE TITLE
Forward slash in spectral path

### ISSUE THREAD

**Issue by JPVentura135** [BU-hammerTeam/PyHammer#6]
If the file with the spectra list doesn't contain the full path, theres an option in the GUI to supply the path. However, this doesn't add a forward slash and the code, when it cannot find a forward slash, appears to add a backslash to the path which then breaks when trying to find the path in Mac OS given that paths in Mac use forward slashes.

**Comment by zephyr5050** [comment]
Has now been resolved. Thanks for letting us know.
