### ISSUE TITLE
Add link to updated IDL Hammer

### ISSUE THREAD

**Issue by jradavenport** [BU-hammerTeam/PyHammer#7]
@kevincovey has allowed me to upload the "official" Hammer version to GitHub here: https://github.com/jradavenport/TheHammer
Which is now on v1.3

While development for the IDL version of The Hammer has ended, minimal support has continued to debug a few problems that have arisen with newer IDL releases.

It may be worth adding a link to the GitHub version of the IDL Hammer to your Readme file.

Can't wait to try PyHammer!

**Comment by aurorayk** [comment]
I have added the github link in the readme. Hope you enjoy PyHammer!
