### ISSUE TITLE
Add a License file

### ISSUE THREAD

**Issue by jradavenport** [BU-hammerTeam/PyHammer#8]
As @jakevdp (and others) [have discussed](http://www.astrobetter.com/blog/2014/03/10/the-whys-and-hows-of-licensing-scientific-code/), it's very good to include a License with code so others know how they can use/modify/etc.

This is super easy, just add a License.md or .txt file in the repo. [Here are some great instructions from GitHub](https://help.github.com/articles/open-source-licensing/)

**Comment by aurorayk** [comment]
Thanks for the suggestion. I hadn't thought of this before. After reading up a bit I was thinking of the [http://choosealicense.com/licenses/mit/](MIT license). Any one else have input before I implement?

**Comment by jakevdp** [comment]
MIT is a great choice :smile:

**Comment by zephyr5050** [comment]
Sounds like a good choice to me. Feel free to go for it.

**Comment by aurorayk** [comment]
Done. Thanks guys.
